In [64]:
import pandas as pd

# CONCATINATE

In [65]:
df1=pd.DataFrame({"acc":[1,2,3],"name":["a","b","c"],"age":[2,3,4]})
df2=pd.DataFrame({"principle":[2,3,5],"interest":[3,4,5]})

In [66]:
pd.concat([df1,df2],axis=1)

   acc name  age  principle  interest
0    1    a    2          2         3
1    2    b    3          3         4
2    3    c    4          5         5

In [67]:
pd.concat([df1,df2],axis=0,ignore_index=True)

   acc name  age  principle  interest
0  1.0    a  2.0        NaN       NaN
1  2.0    b  3.0        NaN       NaN
2  3.0    c  4.0        NaN       NaN
3  NaN  NaN  NaN        2.0       3.0
4  NaN  NaN  NaN        3.0       4.0
5  NaN  NaN  NaN        5.0       5.0

# MERGE

In [68]:
df1=pd.DataFrame({"key":["A","B","C","D"],"inv_val":[99,88,77,66],"acc":[1,2,3,4]})

df2=pd.DataFrame({"key":["E","B","C","Z"],"hel_ratio":[99,88,77,66],"acc":[11,22,33,44]})

In [69]:
df1,df2

(  key  inv_val  acc
 0   A       99    1
 1   B       88    2
 2   C       77    3
 3   D       66    4,
   key  hel_ratio  acc
 0   E         99   11
 1   B         88   22
 2   C         77   33
 3   Z         66   44)

In [70]:
pd.merge(left=df1,right=df2,how="left",on="key")

  key  inv_val  acc_x  hel_ratio  acc_y
0   A       99      1        NaN    NaN
1   B       88      2       88.0   22.0
2   C       77      3       77.0   33.0
3   D       66      4        NaN    NaN

In [71]:
pd.merge(left=df1,right=df2,how="right",on="key",suffixes=("acc_l","acc_r"))

  key  inv_val  accacc_l  hel_ratio  accacc_r
0   E      NaN       NaN         99        11
1   B     88.0       2.0         88        22
2   C     77.0       3.0         77        33
3   Z      NaN       NaN         66        44

In [72]:
df1,df2

(  key  inv_val  acc
 0   A       99    1
 1   B       88    2
 2   C       77    3
 3   D       66    4,
   key  hel_ratio  acc
 0   E         99   11
 1   B         88   22
 2   C         77   33
 3   Z         66   44)

In [73]:
pd.merge(left=df1,right=df2,how="outer",on="key")

  key  inv_val  acc_x  hel_ratio  acc_y
0   A     99.0    1.0        NaN    NaN
1   B     88.0    2.0       88.0   22.0
2   C     77.0    3.0       77.0   33.0
3   D     66.0    4.0        NaN    NaN
4   E      NaN    NaN       99.0   11.0
5   Z      NaN    NaN       66.0   44.0

In [74]:

df3=pd.DataFrame({"key":["E","F","G","Z"],"hel_ratio":[99,88,77,66],"acc":[11,22,33,44]})

In [75]:

df4=pd.DataFrame({"key":["E","I","G","K"],"hel_ratio":[99,88,77,66],"acc":[11,22,33,44]})

In [76]:
df3,df4

(  key  hel_ratio  acc
 0   E         99   11
 1   F         88   22
 2   G         77   33
 3   Z         66   44,
   key  hel_ratio  acc
 0   E         99   11
 1   I         88   22
 2   G         77   33
 3   K         66   44)

In [77]:
pd.merge(left=df3,right=df4,on="key",how="right",suffixes=("df3","df4"))
pd.merge(left=df3,right=df4,on="key",how="outer",suffixes=("df3","df4"),indicator=True)

  key  hel_ratiodf3  accdf3  hel_ratiodf4  accdf4      _merge
0   E          99.0    11.0          99.0    11.0        both
1   F          88.0    22.0           NaN     NaN   left_only
2   G          77.0    33.0          77.0    33.0        both
3   I           NaN     NaN          88.0    22.0  right_only
4   K           NaN     NaN          66.0    44.0  right_only
5   Z          66.0    44.0           NaN     NaN   left_only

In [78]:
df3.merge(df4,on="key")

  key  hel_ratio_x  acc_x  hel_ratio_y  acc_y
0   E           99     11           99     11
1   G           77     33           77     33

# JOIN

In [79]:
df3,df4

(  key  hel_ratio  acc
 0   E         99   11
 1   F         88   22
 2   G         77   33
 3   Z         66   44,
   key  hel_ratio  acc
 0   E         99   11
 1   I         88   22
 2   G         77   33
 3   K         66   44)

In [93]:
df3.join(df2,how="inner",lsuffix="left",rsuffix="right")

Empty DataFrame
Columns: [hel_ratioleft, accleft, key, hel_ratioright, accright]
Index: []

In [94]:
df3,df4

(     hel_ratio  acc
 key
 E           99   11
 F           88   22
 G           77   33
 Z           66   44,
   key  hel_ratio  acc
 0   E         99   11
 1   I         88   22
 2   G         77   33
 3   K         66   44)

In [95]:
df4.join(df3,how="inner",lsuffix="_left",rsuffix="_right")

Empty DataFrame
Columns: [key, hel_ratio_left, acc_left, hel_ratio_right, acc_right]
Index: []

In [111]:
df1.join(df2,how="inner",lsuffix="_left",rsuffix="_right")

     inv_val  acc_left  hel_ratio  acc_right
key
B         88         2         88         22
C         77         3         77         33

# STACKING

In [113]:
df1.stack(),df1

(key
 A    inv_val    99
      acc         1
 B    inv_val    88
      acc         2
 C    inv_val    77
      acc         3
 D    inv_val    66
      acc         4
 dtype: int64,
      inv_val  acc
 key
 A         99    1
 B         88    2
 C         77    3
 D         66    4)

# SAVE DATA TO CSV

In [135]:
titanic=pd.read_csv("train.csv",nrows=10)
titanic.Age.dropna(inplace=True)
titanic.isnull().sum()
titanic["Age"]=titanic.Age.fillna(titanic.groupby("Sex")["Age"].transform("mean"))

In [136]:
titanic["Cabin"]=titanic.Cabin.fillna(titanic.Cabin.mode(),inplace=True)

C:\Users\My PC\AppData\Local\Temp\ipykernel_205612\3013357788.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  titanic["Cabin"]=titanic.Cabin.fillna(titanic.Cabin.mode(),inplace=True)

In [142]:
titanic["Cabin"]=titanic["Cabin"].ffill()

In [145]:
titanic.to_csv("cleaned_titanic.csv")