In [ ]:
import pandas as pd

# LABEL ENCODING 
technique that is used to convert categorical columns into numerical ones so that they can be fited by machine learning models which only take numerical data

In [ ]:
titanic=pd.read_csv("train.csv",nrows=10)

In [ ]:
# nominal data 
titanic.Sex

0      male
1    female
2    female
3    female
4      male
5      male
6      male
7      male
8    female
9    female
Name: Sex, dtype: str

In [ ]:
pd.get_dummies(titanic,columns=["Sex"],dtype=int)

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Sex_female,Sex_male
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,NaN,S,0,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C85,C,1,0
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,S,1,0
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,NaN,S,0,1
5,6,0,3,"Moran, Mr. James",NaN,0,0,330877,8.4583,NaN,Q,0,1
6,7,0,1,"McCarthy, Mr. Timothy J",54.0,0,0,17463,51.8625,E46,S,0,1
7,8,0,3,"Palsson, Master. Gosta Leonard",2.0,3,1,349909,21.0750,NaN,S,0,1
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",27.0,0,2,347742,11.1333,NaN,S,1,0
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",14.0,1,0,237736,30.0708,NaN,C,1,0

In [ ]:
pd.get_dummies(titanic,columns=["Embarked"],dtype=int).sample()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked_C,Embarked_Q,Embarked_S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,0,0,1

# SCI-KIT LEARN
MACHINE LEARNING

In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
# so  OneHotEncoder is an class so to use its property we have to create its object

In [ ]:
one_hot_encoder=OneHotEncoder(sparse_output=False)
# we have created the object name one_hot_encoder and aso in parameter we have done sparse_output=False beacuse to take output in arrays and if we had done sparse_output=True then we would get output in matrix

In [ ]:
encoder_gender=one_hot_encoder.fit_transform(titanic[["Sex"]])
#also WE HAVE USED one_hot_encoder.fit_transform(titanic[["Sex"]]) -> because onehotencoder dont accept the pandas series like 1-D objects so we made it 2D by doimg [[]]

In [ ]:
encoder_gender

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.]])

In [ ]:
one_hot_encoder.categories_
# so,one_hot_encoder.categories_ gives the idea about the number used and what that number represnts

[array(['female', 'male'], dtype=object)]

In [ ]:
one_hot_encoder.inverse_transform(encoder_gender)
# so, onehotencoder.inverse_transform(encoder_gender),does gives the meaning behind that numbers ir what actually that numbers stores
# also, we can write the output also like one_hot_encoder.inverse_transform([1,0],[0,1]) like this and the output will be given according to what number that actually represents

array([['male'],
       ['female'],
       ['female'],
       ['female'],
       ['male'],
       ['male'],
       ['male'],
       ['male'],
       ['female'],
       ['female']], dtype=object)

In [ ]:
df=pd.DataFrame(encoder_gender,columns=one_hot_encoder.categories_)

ValueError: all arrays must be same length

In [ ]:
titanic=pd.concat([titanic,df],axis=1)
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,"(female,)","(male,)"
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0.0,1.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1.0,0.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1.0,0.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1.0,0.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0.0,1.0
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,0.0,1.0
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,0.0,1.0
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,0.0,1.0
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,1.0,0.0
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,1.0,0.0

In [ ]:
# --PRACTICE--
# from sklearn.preprocessing import OneHotEncoder
# one_hot_encoder=OneHotEncoder(sparse_output=False)
# encoded_gender=one_hot_encoder.fit_transform(titanic[[""Sex"]])
# one_hot_encoder.categories_
# one_hot_encoder.inverse_transform(encoded_gender)
# naya_df=pd.DataFrame(encoded_gender,columns=one_hot_encoder.categories_)
# naya_df=pd.concat([titanic,naya_df],axis=1)

In [ ]:
encoded_embarked=one_hot_encoder.fit_transform(titanic[["Embarked"]])
# this one is encoded embarked of titanic but i havent add this one

In [ ]:
encoded_sex_embarked=one_hot_encoder.fit_transform(titanic[["Sex","Embarked"]])
one_hot_encoder.inverse_transform(encoded_sex_embarked)

array([['male', 'S'],
       ['female', 'C'],
       ['female', 'S'],
       ['female', 'S'],
       ['male', 'S'],
       ['male', 'Q'],
       ['male', 'S'],
       ['male', 'S'],
       ['female', 'S'],
       ['female', 'C']], dtype=object)

In [ ]:
one_hot_encoder.categories_,encoded_sex_embarked,one_hot_encoder.inverse_transform(encoded_sex_embarked)

([array(['female', 'male'], dtype=object),
  array(['C', 'Q', 'S'], dtype=object)],
 array([[0., 1., 0., 0., 1.],
        [1., 0., 1., 0., 0.],
        [1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1.],
        [0., 1., 0., 0., 1.],
        [0., 1., 0., 1., 0.],
        [0., 1., 0., 0., 1.],
        [0., 1., 0., 0., 1.],
        [1., 0., 0., 0., 1.],
        [1., 0., 1., 0., 0.]]),
 array([['male', 'S'],
        ['female', 'C'],
        ['female', 'S'],
        ['female', 'S'],
        ['male', 'S'],
        ['male', 'Q'],
        ['male', 'S'],
        ['male', 'S'],
        ['female', 'S'],
        ['female', 'C']], dtype=object))

In [ ]:
import numpy as np

In [ ]:
np.hstack((titanic.values,encoded_sex_embarked))

array([[1, 0, 3, 'Braund, Mr. Owen Harris', 'male', 22.0, 1, 0,
        'A/5 21171', 7.25, nan, 'S', 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0],
       [2, 1, 1, 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
        'female', 38.0, 1, 0, 'PC 17599', 71.2833, 'C85', 'C', 1.0, 0.0,
        1.0, 0.0, 1.0, 0.0, 0.0],
       [3, 1, 3, 'Heikkinen, Miss. Laina', 'female', 26.0, 0, 0,
        'STON/O2. 3101282', 7.925, nan, 'S', 1.0, 0.0, 1.0, 0.0, 0.0,
        0.0, 1.0],
       [4, 1, 1, 'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
        'female', 35.0, 1, 0, '113803', 53.1, 'C123', 'S', 1.0, 0.0, 1.0,
        0.0, 0.0, 0.0, 1.0],
       [5, 0, 3, 'Allen, Mr. William Henry', 'male', 35.0, 0, 0,
        '373450', 8.05, nan, 'S', 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0],
       [6, 0, 3, 'Moran, Mr. James', 'male', nan, 0, 0, '330877', 8.4583,
        nan, 'Q', 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0],
       [7, 0, 1, 'McCarthy, Mr. Timothy J', 'male', 54.0, 0, 0, '17463',
        51.8625, 'E46', 'S', 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0],
       [8, 0, 3, 'Palsson, Master. Gosta Leonard', 'male', 2.0, 3, 1,
        '349909', 21.075, nan, 'S', 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0],
       [9, 1, 3, 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
        'female', 27.0, 0, 2, '347742', 11.1333, nan, 'S', 1.0, 0.0, 1.0,
        0.0, 0.0, 0.0, 1.0],
       [10, 1, 2, 'Nasser, Mrs. Nicholas (Adele Achem)', 'female', 14.0,
        1, 0, '237736', 30.0708, nan, 'C', 1.0, 0.0, 1.0, 0.0, 1.0, 0.0,
        0.0]], dtype=object)

# ORDINAL DATA 
DATA WITH ORDER

In [ ]:
titanic.Embarked

0    S
1    C
2    S
3    S
4    S
5    Q
6    S
7    S
8    S
9    C
Name: Embarked, dtype: str

In [ ]:
# FOR PANDAS 
titanic["EMBARKED_ENCODED"],rule=titanic.Embarked.factorize(sort=True)
#.categorize_==rule
rule
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,"(female,)","(male,)",EMBARKED_ENCODED
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0.0,1.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1.0,0.0,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1.0,0.0,2
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1.0,0.0,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0.0,1.0,2

In [ ]:
rule

Index(['C', 'Q', 'S'], dtype='str')

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
label_encoder=LabelEncoder()
encoded_e=label_encoder.fit_transform(titanic["Embarked"])
label_encoder.classes_

array(['C', 'Q', 'S'], dtype=object)

In [ ]:
final_df=titanic.drop(["Name","Ticket","Embarked","Sex"],axis=1)
final_df["Cabin"]=final_df["Cabin"].notnull().apply(lambda x: 1 if x else 0 )

In [ ]:

final_df

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Cabin,"(female,)","(male,)",EMBARKED_ENCODED
0,1,0,3,22.0,1,0,7.2500,0,0.0,1.0,2
1,2,1,1,38.0,1,0,71.2833,1,1.0,0.0,0
2,3,1,3,26.0,0,0,7.9250,0,1.0,0.0,2
3,4,1,1,35.0,1,0,53.1000,1,1.0,0.0,2
4,5,0,3,35.0,0,0,8.0500,0,0.0,1.0,2
5,6,0,3,NaN,0,0,8.4583,0,0.0,1.0,1
6,7,0,1,54.0,0,0,51.8625,1,0.0,1.0,2
7,8,0,3,2.0,3,1,21.0750,0,0.0,1.0,2
8,9,1,3,27.0,0,2,11.1333,0,1.0,0.0,2
9,10,1,2,14.0,1,0,30.0708,0,1.0,0.0,0

In [ ]:
final_df.to_csv("final_data.csv")